version: '4'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lamp_docker
      MYSQL_USER: lamp_docker
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  www:
    image: php:8.1-apache-buster
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443